[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=--no-dynamic-linker", 
    "-C", "link-arg=-static",
    "-C", "relocation-model=static",
    "-C", "link-arg=-no-pie",
    "-C", "link-arg=-z", 
    "-C", "link-arg=max-page-size=0x1000",
    "-C", "link-arg=--oformat=elf64-x86-64",
]

[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
