[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
runner = "qemu-system-x86_64 -kernel"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-Tkernel/linker.ld",
    "-C", "link-arg=-no-pie"
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
